spring.application.name=BookToMusic


# Server
server.port=8080

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/onion?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# MyBatis
mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=com.booktomusic.dto

# DevTools
spring.devtools.restart.enabled=false

# JWT
jwt.secret=${JWT_SECRET}
jwt.access-token-expiration=3600000

#KAKAO(BOOK)
kakao.api.key=${KAKAO_API_KEY}

#open_ai
openai.api.key=${OPENAI_API_KEY}
openai.api.model=gpt-5-mini

#spotify
spotify.client.id=${SPOTIFY_CLIENT_ID}
spotify.client.secret=${SPOTIFY_CLIENT_SECRET}